#!/bin/bash

DIR=`dirname $0`;
rm $DIR/../composer.lock
composer install --no-interaction --prefer-source

INTERPRET='';
if [ "$1" == "" ]; then
	INTERPRET="php"
else
	INTERPRET=$@
fi

$DIR/../vendor/bin/tester -s -j 5 --colors 1 -c $DIR/config/php-unix.ini -p $INTERPRET $DIR/src
